name: Build on push to any branch
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build
      run: |
        scala-cli compile src
