name: Run the script
on:
  - workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main

    - run: |
        scala-cli run src
      env:
        CAPI_KEY: ${{ secrets.CAPI_KEY }}
